### ISSUE TITLE
default to in-memory store

### ISSUE THREAD

**Issue by michielbdejong** [ripple/ilp-plugin-xrp-paychan#18]
The `_store: new Store()` constructor option cannot be specified in a JSON-stringified [`CONNECTOR_LEDGERS` variable](https://github.com/interledgerjs/ilp-connector#trading), so I think we should make it the default if `store` is set but `_store` is not.

**Comment by sharafian** [comment]
in the connector, you can specify a store by setting `store: true` in the CONNECTOR_LEDGERS field for that plugin (the object with `{"plugin":"...","currency":"...","options":{...}}`). The connector will then create a persistent store and pass it it under the `_store` variable.

I think defaulting to an in-memory store is dangerous, especially for xrp-paychan, because it means you'll lose your claims when you restart, allowing a peer to easily defraud you.

**Comment by michielbdejong** [comment]
ah ok, cool. Let's document that in https://github.com/interledgerjs/ilp-connector#trading

**Comment by michielbdejong** [comment]
Closing this issue here.
